#!/bin/bash
set -e

read -p 'Name of task: '

TRIM=$(echo $REPLY | sed -e 's/\s$//g')
NAME=$(echo "${TRIM// /-}")

TARGET=$(echo "${HOME}/tasks/${NAME}")

if [ -d "${TARGET}" ] 
then
    code "${TARGET}"
else  
  read -p "Are you sure you wish to create ${TARGET} (yes/no)? "
  if [ "$REPLY" == "yes" ]; then
    echo "Creating folder"
    mkdir -p "${TARGET}"
    echo "# Tasks" > "${TARGET}/tasks.xit"
    echo "# References" > "${TARGET}/refs.md"
    echo "# Draft" > "${TARGET}/draft.md"
    code "${TARGET}"
  fi
fi
